"use client"

import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "react-hot-toast";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const isLogin = usePathname().split('/')[1] === 'login' || usePathname().split('/')[1] === 'register' ? true : false

  return (
    <html lang="en">
      <body className={`${inter.className} overflow-hidden`}>
        <main>
          {isLogin === false ?
            <>
              <Header />
              <div className="flex">

                <Sidebar />
                <div className=" w-full max-h-screen overflow-y-auto scrollbar-hide">
                  <Toaster />
                  {children}
                </div>
              </div>
            </>

            :
            <div className=" w-full max-h-screen overflow-y-auto scrollbar-hide">
              <Toaster />
              {children}
            </div>
          }

        </main>
      </body>
    </html>
  );
}
